# Simple Mounts - Ver 1.0 (BETA)
# Author: Nicksarmour

# This plugin is designed to in the most simplest terms, provide simple mount store, summon, and simple customization

#Basic Configuration
Basic:
  max-mounts: 3
  isImmortal: false
  isBreedable: true