# Simple Mounts - Ver 1.0 (BETA)
# Author: Nicksarmour

# This plugin is designed to in the most simplest terms, provide simple mount store, summon, and simple customization

#Basic Configuration
basic:
  max-mounts: 3
  is-immortal: false
  is-breedable: true

#To do with models / texture packs stuff
advanced:
  custom-sounds: true